INSERT INTO details (TYPE,tab,section,OPTION) VALUES ("ATCC","Arcada a tratar/condiciones clinicas","Arcada a tratar","Ambas");
INSERT INTO details (TYPE,tab,section,OPTION) VALUES ("ATCC","Arcada a tratar/condiciones clinicas","Arcada a tratar","Superior");
INSERT INTO details (TYPE,tab,section,OPTION) VALUES ("ATCC","Arcada a tratar/condiciones clinicas","Arcada a tratar","Inferior");
INSERT INTO details (TYPE,tab,section,OPTION) VALUES ("ATCC","Arcada a tratar/condiciones clinicas","Condiciones clinicas","Apiñamiento");
INSERT INTO details (TYPE,tab,section,OPTION) VALUES ("ATCC","Arcada a tratar/condiciones clinicas","Condiciones clinicas","Clase II - Division 1");
INSERT INTO details (TYPE,tab,section,OPTION) VALUES ("ATCC","Arcada a tratar/condiciones clinicas","Condiciones clinicas","Clase III");
INSERT INTO details (TYPE,tab,section,OPTION) VALUES ("ATCC","Arcada a tratar/condiciones clinicas","Condiciones clinicas","Mordida profunda");
INSERT INTO details (TYPE,tab,section,OPTION) VALUES ("ATCC","Arcada a tratar/condiciones clinicas","Condiciones clinicas","Mordida cruzada posterior");
INSERT INTO details (TYPE,tab,section,OPTION) VALUES ("ATCC","Arcada a tratar/condiciones clinicas","Condiciones clinicas","Resalte");
INSERT INTO details (TYPE,tab,section,OPTION) VALUES ("ATCC","Arcada a tratar/condiciones clinicas","Condiciones clinicas","Espaciado");
INSERT INTO details (TYPE,tab,section,OPTION) VALUES ("ATCC","Arcada a tratar/condiciones clinicas","Condiciones clinicas","Clase II - Division 2");
INSERT INTO details (TYPE,tab,section,OPTION) VALUES ("ATCC","Arcada a tratar/condiciones clinicas","Condiciones clinicas","Mordida abierta");
INSERT INTO details (TYPE,tab,section,OPTION) VALUES ("ATCC","Arcada a tratar/condiciones clinicas","Condiciones clinicas","Mordida cruzada anterior");
INSERT INTO details (TYPE,tab,section,OPTION) VALUES ("ATCC","Arcada a tratar/condiciones clinicas","Condiciones clinicas","Arcada estrecha");
INSERT INTO details (TYPE,tab,section,OPTION) VALUES ("RM","Restricciones de movimiento","Restricciones movimiento","Ninguna");
INSERT INTO details (TYPE,tab,section,OPTION) VALUES ("RM","Restricciones de movimiento","Restricciones movimiento","Estos dientes no deben Moverse");
INSERT INTO details (TYPE,tab,section,OPTION) VALUES ("RA","Relacion anteroposterior","Mantener","D");
INSERT INTO details (TYPE,tab,section,OPTION) VALUES ("RA","Relacion anteroposterior","Mantener","I");
INSERT INTO details (TYPE,tab,section,OPTION) VALUES ("RA","Relacion anteroposterior","Mejorar relacion entre caninos","D");
INSERT INTO details (TYPE,tab,section,OPTION) VALUES ("RA","Relacion anteroposterior","Mejorar relacion entre caninos","I");
INSERT INTO details (TYPE,tab,section,OPTION) VALUES ("RA","Relacion anteroposterior","Mejorar relacion entre canino y molar","D");
INSERT INTO details (TYPE,tab,section,OPTION) VALUES ("RA","Relacion anteroposterior","Mejorar relacion entre canino y molar","I");
INSERT INTO details (TYPE,tab,section,OPTION) VALUES ("RS","Resalta sobremordida","Resalte","Mostrar el resalte resultante después de la alinea");
INSERT INTO details (TYPE,tab,section,OPTION) VALUES ("RS","Resalta sobremordida","Resalte","Mantener el resalte inicial (puede requerir DIP).");
INSERT INTO details (TYPE,tab,section,OPTION) VALUES ("RS","Resalta sobremordida","Resalte","Mejorar el resalte resultante con DIP.");
INSERT INTO details (TYPE,tab,section,OPTION) VALUES ("RS","Resalta sobremordida","Sobremordida","Mostrar sobremordida resultante después de la alin");
INSERT INTO details (TYPE,tab,section,OPTION) VALUES ("RS","Resalta sobremordida","Sobremordida","Mantener sobremordida inicial (puede requerir DIP)");
INSERT INTO details (TYPE,tab,section,OPTION) VALUES ("RS","Resalta sobremordida","Sobremordida","Corregir mordida profunda - intruir dientes anteri");
INSERT INTO details (TYPE,tab,section,OPTION) VALUES ("LMMC","Linea media/mordida cruzada","Linea media","Mostrar linea media resultante después de la aline");
INSERT INTO details (TYPE,tab,section,OPTION) VALUES ("LMMC","Linea media/mordida cruzada","Linea media","Mantener linea media inicial (puede requerir DIP)");
INSERT INTO details (TYPE,tab,section,OPTION) VALUES ("LMMC","Linea media/mordida cruzada","Linea media","Mejorar linea media");
INSERT INTO details (TYPE,tab,section,OPTION) VALUES ("LMMC","Linea media/mordida cruzada","Mordida cruzada posterior","Corregir");
INSERT INTO details (TYPE,tab,section,OPTION) VALUES ("LMMC","Linea media/mordida cruzada","Mordida cruzada posterior","No Corregir");
INSERT INTO details (TYPE,tab,section,OPTION) VALUES ("LMMC","Linea media/mordida cruzada","Alineacion sector anterior","Tomar como referencia los margenes gingivales.");
INSERT INTO details (TYPE,tab,section,OPTION) VALUES ("LMMC","Linea media/mordida cruzada","Alineacion sector anterior","Tomar como referencia los bordes incisales.");
INSERT INTO details (TYPE,tab,section,OPTION) VALUES ("MISUP","Movimientos Indicados","Expandir","Preferentemente");
INSERT INTO details (TYPE,tab,section,OPTION) VALUES ("MISUP","Movimientos Indicados","Expandir","Según sea necesario");
INSERT INTO details (TYPE,tab,section,OPTION) VALUES ("MISUP","Movimientos Indicados","Expandir","No");
INSERT INTO details (TYPE,tab,section,OPTION) VALUES ("MISUP","Movimientos Indicados","Poinclinar","Preferentemente");
INSERT INTO details (TYPE,tab,section,OPTION) VALUES ("MISUP","Movimientos Indicados","Poinclinar","Según sea necesario");
INSERT INTO details (TYPE,tab,section,OPTION) VALUES ("MISUP","Movimientos Indicados","Poinclinar","No");
INSERT INTO details (TYPE,tab,section,OPTION) VALUES ("MISUP","Movimientos Indicados","DIP-Anterior","Preferentemente");
INSERT INTO details (TYPE,tab,section,OPTION) VALUES ("MISUP","Movimientos Indicados","DIP-Anterior","Según sea necesario");
INSERT INTO details (TYPE,tab,section,OPTION) VALUES ("MISUP","Movimientos Indicados","DIP-Anterior","No");
INSERT INTO details (TYPE,tab,section,OPTION) VALUES ("MISUP","Movimientos Indicados","DIP-Derecha posterior","Preferentemente");
INSERT INTO details (TYPE,tab,section,OPTION) VALUES ("MISUP","Movimientos Indicados","DIP-Derecha posterior","Según sea necesario");
INSERT INTO details (TYPE,tab,section,OPTION) VALUES ("MISUP","Movimientos Indicados","DIP-Derecha posterior","No");
INSERT INTO details (TYPE,tab,section,OPTION) VALUES ("MISUP","Movimientos Indicados","DIP-Izquierda posterior","Preferentemente");
INSERT INTO details (TYPE,tab,section,OPTION) VALUES ("MISUP","Movimientos Indicados","DIP-Izquierda posterior","Según sea necesario");
INSERT INTO details (TYPE,tab,section,OPTION) VALUES ("MISUP","Movimientos Indicados","DIP-Izquierda posterior","No");
INSERT INTO details (TYPE,tab,section,OPTION) VALUES ("MIINF","Movimientos Indicados","Expandir","Preferentemente");
INSERT INTO details (TYPE,tab,section,OPTION) VALUES ("MIINF","Movimientos Indicados","Expandir","Según sea necesario");
INSERT INTO details (TYPE,tab,section,OPTION) VALUES ("MIINF","Movimientos Indicados","Expandir","No");
INSERT INTO details (TYPE,tab,section,OPTION) VALUES ("MIINF","Movimientos Indicados","Poinclinar","Preferentemente");
INSERT INTO details (TYPE,tab,section,OPTION) VALUES ("MIINF","Movimientos Indicados","Poinclinar","Según sea necesario");
INSERT INTO details (TYPE,tab,section,OPTION) VALUES ("MIINF","Movimientos Indicados","Poinclinar","No");
INSERT INTO details (TYPE,tab,section,OPTION) VALUES ("MIINF","Movimientos Indicados","DIP-Anterior","Preferentemente");
INSERT INTO details (TYPE,tab,section,OPTION) VALUES ("MIINF","Movimientos Indicados","DIP-Anterior","Según sea necesario");
INSERT INTO details (TYPE,tab,section,OPTION) VALUES ("MIINF","Movimientos Indicados","DIP-Anterior","No");
INSERT INTO details (TYPE,tab,section,OPTION) VALUES ("MIINF","Movimientos Indicados","DIP-Derecha posterior","Preferentemente");
INSERT INTO details (TYPE,tab,section,OPTION) VALUES ("MIINF","Movimientos Indicados","DIP-Derecha posterior","Según sea necesario");
INSERT INTO details (TYPE,tab,section,OPTION) VALUES ("MIINF","Movimientos Indicados","DIP-Derecha posterior","No");
INSERT INTO details (TYPE,tab,section,OPTION) VALUES ("MIINF","Movimientos Indicados","DIP-Izquierda posterior","Preferentemente");
INSERT INTO details (TYPE,tab,section,OPTION) VALUES ("MIINF","Movimientos Indicados","DIP-Izquierda posterior","Según sea necesario");
INSERT INTO details (TYPE,tab,section,OPTION) VALUES ("MIINF","Movimientos Indicados","DIP-Izquierda posterior","No");
INSERT INTO details (TYPE,tab,section,OPTION) VALUES ("AT","Ataches","Ataches","Colocar ataches según sea necesario");
INSERT INTO details (TYPE,tab,section,OPTION) VALUES ("AT","Ataches","Ataches","Colocar ataches en:");
