INSERT INTO details (TYPE, description, OPTION) VALUES ('AAT','Arcada a Tratar','{"name":"Ambas"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('AAT','Arcada a Tratar','{"name":"Superior"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('AAT','Arcada a Tratar','{"name":"Inferior"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('CC','Condiciones clínicas','{"name":"Apiñamiento"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('CC','Condiciones clínicas','{"name":"Clase II - Division 1"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('CC','Condiciones clínicas','{"name":"Clase III"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('CC','Condiciones clínicas','{"name":"Mordida profunda"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('CC','Condiciones clínicas','{"name":"Mordida cruzada posterior"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('CC','Condiciones clínicas','{"name":"Resalte"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('CC','Condiciones clínicas','{"name":"Espaciado"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('CC','Condiciones clínicas','{"name":"Clase II - Division 2"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('CC','Condiciones clínicas','{"name":"Mordida abierta"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('CC','Condiciones clínicas','{"name":"Mordida cruzada anterior"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('CC','Condiciones clínicas','{"name":"Arcada estrecha"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RDM','Restricciones de movimiento','{"name":"Ninguna"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RDM','Restricciones de movimiento','{"name":"18"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RDM','Restricciones de movimiento','{"name":"1"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RDM','Restricciones de movimiento','{"name":"16"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RDM','Restricciones de movimiento','{"name":"15"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RDM','Restricciones de movimiento','{"name":"14"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RDM','Restricciones de movimiento','{"name":"13"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RDM','Restricciones de movimiento','{"name":"11"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RDM','Restricciones de movimiento','{"name":"48"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RDM','Restricciones de movimiento','{"name":"47"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RDM','Restricciones de movimiento','{"name":"46"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RDM','Restricciones de movimiento','{"name":"45"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RDM','Restricciones de movimiento','{"name":"44"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RDM','Restricciones de movimiento','{"name":"43"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RDM','Restricciones de movimiento','{"name":"42"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RDM','Restricciones de movimiento','{"name":"41"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RDM','Restricciones de movimiento','{"name":"21"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RDM','Restricciones de movimiento','{"name":"22"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RDM','Restricciones de movimiento','{"name":"23"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RDM','Restricciones de movimiento','{"name":"24"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RDM','Restricciones de movimiento','{"name":"25"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RDM','Restricciones de movimiento','{"name":"26"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RDM','Restricciones de movimiento','{"name":"27"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RDM','Restricciones de movimiento','{"name":"28"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RDM','Restricciones de movimiento','{"name":"31"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RDM','Restricciones de movimiento','{"name":"32"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RDM','Restricciones de movimiento','{"name":"33"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RDM','Restricciones de movimiento','{"name":"34"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RDM','Restricciones de movimiento','{"name":"35"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RDM','Restricciones de movimiento','{"name":"36"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RDM','Restricciones de movimiento','{"name":"37"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RDM','Restricciones de movimiento','{"name":"38"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RA','Relacion anteroposterior','{"name":"Mantener","option":"D"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RA','Relacion anteroposterior','{"name":"Mantener","option":"D"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RA','Relacion anteroposterior','{"name":"Mantener","option":"D"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RA','Relacion anteroposterior','{"name":"Mantener","option":"D"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RA','Relacion anteroposterior','{"name":"Mantener","option":"D"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RA','Relacion anteroposterior','{"name":"Mantener","option":"D"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RM','Reslate/Mordida','{"name":"Mantener","option":"D"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RM','Reslate/Mordida','{"name":"Mantener","option":"D"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RM','Reslate/Mordida','{"name":"Mantener","option":"D"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RM','Reslate/Mordida','{"name":"Mantener","option":"D"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RM','Reslate/Mordida','{"name":"Mantener","option":"D"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RM','Reslate/Mordida','{"name":"Mantener","option":"D"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RM','Reslate/Mordida','{"name":"Mantener","option":"D"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('LM','Linea media','{"name":"Mantener","option":"D"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('LM','Linea media','{"name":"Mantener","option":"D"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('LM','Linea media','{"name":"Mantener","option":"D"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('LM','Linea media','{"name":"Mantener","option":"D"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('LM','Linea media','{"name":"Mantener","option":"D"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('LM','Linea media','{"name":"Mantener","option":"D"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('MCP','Mordida cruzada posterior','{"name":"Corregir"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('MCP','Mordida cruzada posterior','{"name":"No corregir"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('ASA','Alineacion sector anterior','{"name":"Tomar como referencia los margenes gingivales."}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('ASA','Alineacion sector anterior','{"name":"Tomar como referencia los bordes incisales."}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('MI','Movimientos indicados','{"name":"Resolver superior","type":"Expandir","option":"Preferentemente"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('MI','Movimientos indicados','{"name":"Resolver superior","type":"Expandir","option":"Preferentemente"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('MI','Movimientos indicados','{"name":"Resolver superior","type":"Expandir","option":"Preferentemente"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('MI','Movimientos indicados','{"name":"Resolver superior","type":"Expandir","option":"Preferentemente"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('MI','Movimientos indicados','{"name":"Resolver superior","type":"Expandir","option":"Preferentemente"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('MI','Movimientos indicados','{"name":"Resolver superior","type":"Expandir","option":"Preferentemente"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('MI','Movimientos indicados','{"name":"Resolver superior","type":"Expandir","option":"Preferentemente"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('MI','Movimientos indicados','{"name":"Resolver superior","type":"Expandir","option":"Preferentemente"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('MI','Movimientos indicados','{"name":"Resolver superior","type":"Expandir","option":"Preferentemente"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('MI','Movimientos indicados','{"name":"Resolver superior","type":"Expandir","option":"Preferentemente"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('MI','Movimientos indicados','{"name":"Resolver superior","type":"Expandir","option":"Preferentemente"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('MI','Movimientos indicados','{"name":"Resolver superior","type":"Expandir","option":"Preferentemente"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('MI','Movimientos indicados','{"name":"Resolver superior","type":"Expandir","option":"Preferentemente"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('MI','Movimientos indicados','{"name":"Resolver superior","type":"Expandir","option":"Preferentemente"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('MI','Movimientos indicados','{"name":"Resolver superior","type":"Expandir","option":"Preferentemente"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('MI','Movimientos indicados','{"name":"Resolver superior","type":"Expandir","option":"Preferentemente"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('MI','Movimientos indicados','{"name":"Resolver superior","type":"Expandir","option":"Preferentemente"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('MI','Movimientos indicados','{"name":"Resolver superior","type":"Expandir","option":"Preferentemente"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('MI','Movimientos indicados','{"name":"Resolver superior","type":"Expandir","option":"Preferentemente"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('MI','Movimientos indicados','{"name":"Resolver superior","type":"Expandir","option":"Preferentemente"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('MI','Movimientos indicados','{"name":"Resolver superior","type":"Expandir","option":"Preferentemente"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('MI','Movimientos indicados','{"name":"Resolver superior","type":"Expandir","option":"Preferentemente"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('MI','Movimientos indicados','{"name":"Resolver superior","type":"Expandir","option":"Preferentemente"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('MI','Movimientos indicados','{"name":"Resolver superior","type":"Expandir","option":"Preferentemente"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('MI','Movimientos indicados','{"name":"Resolver superior","type":"Expandir","option":"Preferentemente"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('MI','Movimientos indicados','{"name":"Resolver superior","type":"Expandir","option":"Preferentemente"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('MI','Movimientos indicados','{"name":"Resolver superior","type":"Expandir","option":"Preferentemente"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('MI','Movimientos indicados','{"name":"Resolver superior","type":"Expandir","option":"Preferentemente"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('MI','Movimientos indicados','{"name":"Resolver superior","type":"Expandir","option":"Preferentemente"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('MI','Movimientos indicados','{"name":"Resolver superior","type":"Expandir","option":"Preferentemente"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('AT','Ataches','{"name":"Colocar ataches según sea necesario"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('AT','Ataches','{"name":"Colocar ataches en","option":"18"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('AT','Ataches','{"name":"Colocar ataches en","option":"18"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('AT','Ataches','{"name":"Colocar ataches en","option":"18"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('AT','Ataches','{"name":"Colocar ataches en","option":"18"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('AT','Ataches','{"name":"Colocar ataches en","option":"18"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('AT','Ataches','{"name":"Colocar ataches en","option":"18"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('AT','Ataches','{"name":"Colocar ataches en","option":"18"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('AT','Ataches','{"name":"Colocar ataches en","option":"18"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('AT','Ataches','{"name":"Colocar ataches en","option":"18"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('AT','Ataches','{"name":"Colocar ataches en","option":"18"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('AT','Ataches','{"name":"Colocar ataches en","option":"18"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('AT','Ataches','{"name":"Colocar ataches en","option":"18"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('AT','Ataches','{"name":"Colocar ataches en","option":"18"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('AT','Ataches','{"name":"Colocar ataches en","option":"18"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('AT','Ataches','{"name":"Colocar ataches en","option":"18"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('AT','Ataches','{"name":"Colocar ataches en","option":"18"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('AT','Ataches','{"name":"Colocar ataches en","option":"18"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('AT','Ataches','{"name":"Colocar ataches en","option":"18"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('AT','Ataches','{"name":"Colocar ataches en","option":"18"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('AT','Ataches','{"name":"Colocar ataches en","option":"18"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('AT','Ataches','{"name":"Colocar ataches en","option":"18"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('AT','Ataches','{"name":"Colocar ataches en","option":"18"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('AT','Ataches','{"name":"Colocar ataches en","option":"18"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('AT','Ataches','{"name":"Colocar ataches en","option":"18"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('AT','Ataches','{"name":"Colocar ataches en","option":"18"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('AT','Ataches','{"name":"Colocar ataches en","option":"18"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('AT','Ataches','{"name":"Colocar ataches en","option":"18"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('AT','Ataches','{"name":"Colocar ataches en","option":"18"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('AT','Ataches','{"name":"Colocar ataches en","option":"18"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('AT','Ataches','{"name":"Colocar ataches en","option":"18"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('AT','Ataches','{"name":"Colocar ataches en","option":"18"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('AT','Ataches','{"name":"Colocar ataches en","option":"18"}');
