INSERT INTO details (TYPE, description, OPTION) VALUES ('AAT','Arcada a Tratar','{"option":"Ambas"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('AAT','Arcada a Tratar','{"option":"Superior"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('AAT','Arcada a Tratar','{"option":"Inferior"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('CC','Condiciones clínicas','{"option":"Apiñamiento"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('CC','Condiciones clínicas','{"option":"Clase II - Division 1"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('CC','Condiciones clínicas','{"option":"Clase III"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('CC','Condiciones clínicas','{"option":"Mordida profunda"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('CC','Condiciones clínicas','{"option":"Mordida cruzada posterior"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('CC','Condiciones clínicas','{"option":"Resalte"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('CC','Condiciones clínicas','{"option":"Espaciado"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('CC','Condiciones clínicas','{"option":"Clase II - Division 2"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('CC','Condiciones clínicas','{"option":"Mordida abierta"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('CC','Condiciones clínicas','{"option":"Mordida cruzada anterior"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('CC','Condiciones clínicas','{"option":"Arcada estrecha"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RDM','Restricciones de movimiento','{"option":"Ninguna"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RDM','Restricciones de movimiento','{"option":"18"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RDM','Restricciones de movimiento','{"option":"1"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RDM','Restricciones de movimiento','{"option":"16"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RDM','Restricciones de movimiento','{"option":"15"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RDM','Restricciones de movimiento','{"option":"14"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RDM','Restricciones de movimiento','{"option":"13"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RDM','Restricciones de movimiento','{"option":"11"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RDM','Restricciones de movimiento','{"option":"48"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RDM','Restricciones de movimiento','{"option":"47"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RDM','Restricciones de movimiento','{"option":"46"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RDM','Restricciones de movimiento','{"option":"45"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RDM','Restricciones de movimiento','{"option":"44"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RDM','Restricciones de movimiento','{"option":"43"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RDM','Restricciones de movimiento','{"option":"42"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RDM','Restricciones de movimiento','{"option":"41"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RDM','Restricciones de movimiento','{"option":"21"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RDM','Restricciones de movimiento','{"option":"22"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RDM','Restricciones de movimiento','{"option":"23"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RDM','Restricciones de movimiento','{"option":"24"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RDM','Restricciones de movimiento','{"option":"25"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RDM','Restricciones de movimiento','{"option":"26"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RDM','Restricciones de movimiento','{"option":"27"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RDM','Restricciones de movimiento','{"option":"28"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RDM','Restricciones de movimiento','{"option":"31"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RDM','Restricciones de movimiento','{"option":"32"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RDM','Restricciones de movimiento','{"option":"33"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RDM','Restricciones de movimiento','{"option":"34"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RDM','Restricciones de movimiento','{"option":"35"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RDM','Restricciones de movimiento','{"option":"36"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RDM','Restricciones de movimiento','{"option":"37"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RDM','Restricciones de movimiento','{"option":"38"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RA','Relacion anteroposterior','{"option":{"name":"Mantener","option":"D"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RA','Relacion anteroposterior','{"option":{"name":"Mantener","option":"D"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RA','Relacion anteroposterior','{"option":{"name":"Mantener","option":"D"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RA','Relacion anteroposterior','{"option":{"name":"Mantener","option":"D"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RA','Relacion anteroposterior','{"option":{"name":"Mantener","option":"D"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RA','Relacion anteroposterior','{"option":{"name":"Mantener","option":"D"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RM','Reslate/Mordida','{"option":{"name":"Mantener","option":"D"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RM','Reslate/Mordida','{"option":{"name":"Mantener","option":"D"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RM','Reslate/Mordida','{"option":{"name":"Mantener","option":"D"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RM','Reslate/Mordida','{"option":{"name":"Mantener","option":"D"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RM','Reslate/Mordida','{"option":{"name":"Mantener","option":"D"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RM','Reslate/Mordida','{"option":{"name":"Mantener","option":"D"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('RM','Reslate/Mordida','{"option":{"name":"Mantener","option":"D"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('LM','Linea media','{"option":{"name":"Mantener","option":"D"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('LM','Linea media','{"option":{"name":"Mantener","option":"D"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('LM','Linea media','{"option":{"name":"Mantener","option":"D"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('LM','Linea media','{"option":{"name":"Mantener","option":"D"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('LM','Linea media','{"option":{"name":"Mantener","option":"D"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('LM','Linea media','{"option":{"name":"Mantener","option":"D"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('MCP','Mordida cruzada posterior','{"option":"Corregir"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('MCP','Mordida cruzada posterior','{"option":"No corregir"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('ASA','Alineacion sector anterior','{"option":"Tomar como referencia los margenes gingivales."}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('ASA','Alineacion sector anterior','{"option":"Tomar como referencia los bordes incisales."}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('MI','Movimientos indicados','{"option":{"name":"Resolver superior","type":"Expandir","option":"Preferentemente"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('MI','Movimientos indicados','{"option":{"name":"Resolver superior","type":"Expandir","option":"Preferentemente"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('MI','Movimientos indicados','{"option":{"name":"Resolver superior","type":"Expandir","option":"Preferentemente"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('MI','Movimientos indicados','{"option":{"name":"Resolver superior","type":"Expandir","option":"Preferentemente"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('MI','Movimientos indicados','{"option":{"name":"Resolver superior","type":"Expandir","option":"Preferentemente"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('MI','Movimientos indicados','{"option":{"name":"Resolver superior","type":"Expandir","option":"Preferentemente"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('MI','Movimientos indicados','{"option":{"name":"Resolver superior","type":"Expandir","option":"Preferentemente"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('MI','Movimientos indicados','{"option":{"name":"Resolver superior","type":"Expandir","option":"Preferentemente"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('MI','Movimientos indicados','{"option":{"name":"Resolver superior","type":"Expandir","option":"Preferentemente"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('MI','Movimientos indicados','{"option":{"name":"Resolver superior","type":"Expandir","option":"Preferentemente"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('MI','Movimientos indicados','{"option":{"name":"Resolver superior","type":"Expandir","option":"Preferentemente"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('MI','Movimientos indicados','{"option":{"name":"Resolver superior","type":"Expandir","option":"Preferentemente"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('MI','Movimientos indicados','{"option":{"name":"Resolver superior","type":"Expandir","option":"Preferentemente"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('MI','Movimientos indicados','{"option":{"name":"Resolver superior","type":"Expandir","option":"Preferentemente"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('MI','Movimientos indicados','{"option":{"name":"Resolver superior","type":"Expandir","option":"Preferentemente"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('MI','Movimientos indicados','{"option":{"name":"Resolver superior","type":"Expandir","option":"Preferentemente"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('MI','Movimientos indicados','{"option":{"name":"Resolver superior","type":"Expandir","option":"Preferentemente"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('MI','Movimientos indicados','{"option":{"name":"Resolver superior","type":"Expandir","option":"Preferentemente"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('MI','Movimientos indicados','{"option":{"name":"Resolver superior","type":"Expandir","option":"Preferentemente"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('MI','Movimientos indicados','{"option":{"name":"Resolver superior","type":"Expandir","option":"Preferentemente"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('MI','Movimientos indicados','{"option":{"name":"Resolver superior","type":"Expandir","option":"Preferentemente"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('MI','Movimientos indicados','{"option":{"name":"Resolver superior","type":"Expandir","option":"Preferentemente"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('MI','Movimientos indicados','{"option":{"name":"Resolver superior","type":"Expandir","option":"Preferentemente"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('MI','Movimientos indicados','{"option":{"name":"Resolver superior","type":"Expandir","option":"Preferentemente"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('MI','Movimientos indicados','{"option":{"name":"Resolver superior","type":"Expandir","option":"Preferentemente"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('MI','Movimientos indicados','{"option":{"name":"Resolver superior","type":"Expandir","option":"Preferentemente"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('MI','Movimientos indicados','{"option":{"name":"Resolver superior","type":"Expandir","option":"Preferentemente"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('MI','Movimientos indicados','{"option":{"name":"Resolver superior","type":"Expandir","option":"Preferentemente"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('MI','Movimientos indicados','{"option":{"name":"Resolver superior","type":"Expandir","option":"Preferentemente"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('MI','Movimientos indicados','{"option":{"name":"Resolver superior","type":"Expandir","option":"Preferentemente"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('AT','Ataches','{"option":"Colocar ataches según sea necesario"}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('AT','Ataches','{"option":{"name":"Colocar ataches en","option":"18"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('AT','Ataches','{"option":{"name":"Colocar ataches en","option":"18"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('AT','Ataches','{"option":{"name":"Colocar ataches en","option":"18"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('AT','Ataches','{"option":{"name":"Colocar ataches en","option":"18"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('AT','Ataches','{"option":{"name":"Colocar ataches en","option":"18"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('AT','Ataches','{"option":{"name":"Colocar ataches en","option":"18"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('AT','Ataches','{"option":{"name":"Colocar ataches en","option":"18"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('AT','Ataches','{"option":{"name":"Colocar ataches en","option":"18"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('AT','Ataches','{"option":{"name":"Colocar ataches en","option":"18"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('AT','Ataches','{"option":{"name":"Colocar ataches en","option":"18"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('AT','Ataches','{"option":{"name":"Colocar ataches en","option":"18"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('AT','Ataches','{"option":{"name":"Colocar ataches en","option":"18"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('AT','Ataches','{"option":{"name":"Colocar ataches en","option":"18"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('AT','Ataches','{"option":{"name":"Colocar ataches en","option":"18"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('AT','Ataches','{"option":{"name":"Colocar ataches en","option":"18"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('AT','Ataches','{"option":{"name":"Colocar ataches en","option":"18"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('AT','Ataches','{"option":{"name":"Colocar ataches en","option":"18"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('AT','Ataches','{"option":{"name":"Colocar ataches en","option":"18"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('AT','Ataches','{"option":{"name":"Colocar ataches en","option":"18"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('AT','Ataches','{"option":{"name":"Colocar ataches en","option":"18"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('AT','Ataches','{"option":{"name":"Colocar ataches en","option":"18"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('AT','Ataches','{"option":{"name":"Colocar ataches en","option":"18"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('AT','Ataches','{"option":{"name":"Colocar ataches en","option":"18"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('AT','Ataches','{"option":{"name":"Colocar ataches en","option":"18"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('AT','Ataches','{"option":{"name":"Colocar ataches en","option":"18"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('AT','Ataches','{"option":{"name":"Colocar ataches en","option":"18"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('AT','Ataches','{"option":{"name":"Colocar ataches en","option":"18"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('AT','Ataches','{"option":{"name":"Colocar ataches en","option":"18"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('AT','Ataches','{"option":{"name":"Colocar ataches en","option":"18"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('AT','Ataches','{"option":{"name":"Colocar ataches en","option":"18"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('AT','Ataches','{"option":{"name":"Colocar ataches en","option":"18"}}');
INSERT INTO details (TYPE, description, OPTION) VALUES ('AT','Ataches','{"option":{"name":"Colocar ataches en","option":"18"}}');
